spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.ssl.truststore.location=classpath:kafka-ca.pem
spring.kafka.properties.ssl.truststore.type=PEM