spring.application.name=search_event_consumer
server.port=9093
spring.profiles.active=local
# AWS
spring.cloud.aws.region.static=ap-south-1
spring.cloud.aws.secretsmanager.region=ap-south-1
spring.config.import=aws-secretsmanager:daily_note_secret_manager

# Elasticsearch
spring.elasticsearch.uris=${ELASTICSEARCH_URL}
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}

# ==========================
# KAFKA
# ==========================

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

#spring.kafka.properties.ssl.truststore.location=${KAFKA_CA_PATH:src/main/resources/kafka-ca.pem}
#spring.kafka.properties.ssl.truststore.type=PEM

# Consumer
spring.kafka.consumer.group-id=task-search-group-v2
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false

# Listener
spring.kafka.listener.ack-mode=manual

# ==========================
# KAFKA DEBUG LOGS
# ==========================

logging.level.org.springframework.kafka=DEBUG
logging.level.org.springframework.kafka.listener=DEBUG
logging.level.org.apache.kafka=DEBUG
logging.level.org.apache.kafka.clients.consumer=DEBUG
logging.level.org.apache.kafka.clients.NetworkClient=DEBUG

logging.level.com.daily_note.search_event_consumer=DEBUG

spring.jmx.enabled=false
spring.main.banner-mode=off
spring.kafka.properties.enable.metrics.push= false