spring.application.name=search_text_app
# 3. AWS Configuration
spring.cloud.aws.region.static=ap-south-1
spring.cloud.aws.secretsmanager.region=ap-south-1
spring.config.import=aws-secretsmanager:daily_note_secret_manager

# Server Port Config
server.port=9092