spring.application.name=search_text_app
# 3. AWS Configuration
spring.cloud.aws.region.static=ap-south-1
spring.cloud.aws.secretsmanager.region=ap-south-1
spring.config.import=aws-secretsmanager:daily_note_secret_manager
# Server Port Config
server.port=9092
# Elastic Search Configuration
spring.elasticsearch.uris=${ELASTICSEARCH_URL}
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}
spring.jmx.enabled=false
spring.main.banner-mode=off
