# DynamoDB Local - Docker
aws.dynamodb.endpoint=http://localhost:8000
aws.region=ap-south-1

# Dummy credentials for DynamoDB Local
aws.access-key=local
aws.secret-key=local

# Other local settings
spring.application.name=daily-note

server.port=9096